FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o weather-http ./cmd/http

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
WORKDIR /bin
COPY --from=builder /app/weather-http .
EXPOSE 8080
ENTRYPOINT ["./weather-http"]

